### ISSUE TITLE
Issues with installation on ST3 for OSX  

### ISSUE THREAD

**Issue by davidmarble** [SublimeText-Markdown/MarkdownEditing#115]
I installed 2.0.3 on ST3 for OSX via package manager, and immediately on restart got this popup:

> Error loading syntax file "Packages/Markdown/Markdown.tmLanguage": Unable to open Packages/Markdown/Markdown.tmLanguage

This happens on every startup and MarkdownEditing doesn't seem to work.

**Comment by jargnar** [comment]
@oli Thank you! Closing all open files and restarting ST3 fixed the issue for me too!

**Comment by tomzx** [comment]
Just to add a note for those that may still have the issue even after restarting ST3. You may have to re-enable Markdown for the offending tabs to appear so that you may close them.

**Comment by galambalazs** [comment]
I had this appear on Windows. Only way I could get that message to not appear and this plugin to work was to re-enable the default Markdown plugin. Now it seems to be ok. -

What's the catch?

Is it wrong if they are enabled side-by-side?

**Comment by guiambros** [comment]
@rralian: you can safely ignore the error. This is because the default Markdown language that ships with ST3 was automatically disabled by Markdown Extended (this plugin), hence the presence of "markdown" within the `ignored_packages`.

If you're still having problems, have you tried installing Monokai Extended, and then enabling the new theme?  See my commend a #108. This solved for me.
