### ISSUE TITLE
hitting Return is not giving me bullet point

### ISSUE THREAD

**Issue by Dellu** [SublimeText-Markdown/MarkdownEditing#189]
A strange problem. Normally, starting up a bullet point and hitting return would give me another bullet point. 

- point one
- point two

That is: the auto-completion of the bullet points (-) is  is suddenly broken in my ST3. I think the issue goes beyond MarkdownEditing (as Markdown Extended is also facing the same issue). 
- I removed and installed all of my markdown related packages, with no luck. 

if anybody has a clue what have gone wrong, I would appreciate!

**Comment by felixhao28** [comment]
I guess it is not a MarkdownEditing issue. Maybe you have overridden/changed "Extend list" shortcut?

**Comment by felixhao28** [comment]
This is issue cannot be reproduced by me. @Dellu, is this still troubling you?

**Comment by Dellu** [comment]
I am sorry, I am not using ST3 anymore.

**Comment by felixhao28** [comment]
That's alright. Solves the issue anyway.

**Comment by feeela** [comment]
@maliayas Please note this developer behavior above…

> That's alright. Solves the issue anyway.

@felixhao28 What the fuck? You wait until users stop using Sublime and then close the tickets? This issue is still open and is definitly something that worked in ST2 but is now broken in ST3. The original issue posted above does still apply in a fresh install of Sublime Text 3. Please don't close tickets merely because you failed to understand them.

Can you please comment on which part of the issue is either unclear or not reproducable, since I see exactly the same false behavior.

**Comment by feeela** [comment]
@maliayas Please reopen.

**Comment by deathaxe** [comment]
This issue was closed, because bullets are added as expected. The following screencast illustrates the behavior of current MarkdownEditing 3.x / ST3176 / Windows 11.

![Animation](https://user-images.githubusercontent.com/16542113/144287182-f3a1a2df-a0f8-4598-8f3a-24b229e90fee.png)

Please note that all those functions rely on key bindings. Those can easily be overwritten by any other plugin or your personal key bindings in _User/Default.sublime-keymap_. MarkdownEditing can't prevent this from happening.

You could run `sublime.log_commands(True)` from ST's console and check, which command is executed when hitting <kbd>enter</kbd>.

The command bound by MarkdownEditing is:
   `command: insert_snippet {"contents": "${TM_CURRENT_LINE/^(?:\\s*((?:>\\s*)*)([-+*])(\\s+)).*/\n$1$2$3/}"}`

**Comment by felixhao28** [comment]
@feeela the issue was closed because I could not reproduce it. I could've phrased that a little bit better, sorry for that. The same symptom reappearing does not always mean it is caused by the same underlying issue. You see, a bug can be fixed for a while and reappear some patches later for very different reasons. In that case, feel free to open another issue.
