### ISSUE TITLE
FullScreenStatus and centering text

### ISSUE THREAD

**Issue by vongoh** [SublimeText-Markdown/MarkdownEditing#191]
MarkdownEditing is using the FullScreenStatus plugin to keep the cursor centered in the screen in `.md` documents.

I know this question is not directly related to MarkdownEditing per say - but does anyone know how to activate this feature globally in ST?

I edit markdown documents constantly and its such a simple but awesome feature.  How can we get this working in other document types?  Anyone?

**Comment by towertop** [comment]
Came to the same error as ot-joe-ocampo .

I'm using Sublime 2.0.2 Build 2221, with Windows 8. Meanwhile I saw MarkdownEditing was marked working with ST2/ST3 at https://packagecontrol.io/packages/MarkdownEditing .

@maliayas 
Maybe you can check and correct the label on package control repository. It is misleading.
Actually I hope it really support ST2. It is awesome.

**Comment by maliayas** [comment]
Firstly a list should be created that contains things we don't support in ST2. Then we can decide to either port them to ST2 or remove ST2 support flag. Any help appreciated.

**Comment by vongoh** [comment]
@maliayas   fyi I opened this issue some time ago and never had a chance to get back to it - but I created the `.py` file , saved it,  got no result in any other files than markdown files.   FullScreenStatus is installed.

ie. the cursor still only stays screen centered in `.md` files.  Is there anything else I need to do to get the cursor centered in .`html`, .`css`. `.scss`,  `.php` etc?

**Comment by maliayas** [comment]
It may not work in ST2, in case you're using that. Otherwise I don't know the reason. Above code normally should enable centering on distraction free mode. Note that if ST is not on distraction free mode, it won't work. If that's what you want, remove the `if on_distraction_free():` line. Then it will work always and not require FullScreenStatus plugin (it just helps to detect if ST is full screen or in distraction free mode).

**Comment by maliayas** [comment]
@felixhao28 I think we can close this issue.
