### ISSUE TITLE
Error loading syntax File

### ISSUE THREAD

**Issue by CMCDragonkai** [SublimeText-Markdown/MarkdownEditing#205]
I'm getting a message after installing this using Package Control in Sublime Text 3 Build 3059:

```
Error loading syntax file
"Package/Markdown/Markdown.tmLanguage": Unable to open Package/Markdown/Markdown.tmLanguage
```

**Comment by OdinsHat** [comment]
The workaround of closing any open markdown files worked. Would it be worth mentioning this potential issue in the installation instructions and then this can be closed?

**Comment by felixhao28** [comment]
It is definitely worth mentioning in the installation instructions (e.g. closing markdown files before installing this plugin), but @maliayas is a busy man.

**Comment by tdegeus** [comment]
This happed to me on sublime 4113. I tried what was mentioned: I removed the package (and all configuration files), closed all files, and tried reinstalling. However, the problem keep reappearing

**Comment by deathaxe** [comment]
This happens because default Markdown package is disabled while syntax assignment is not updated for any open markdown files. You can either close them all and reopen manually or try out 3.0.0 ;) which does exactly that.

To learn how to opt-in, you may have a look at https://sublimetext-markdown.github.io/MarkdownEditing/install
