### ISSUE TITLE
Remove HTML Tab Completion

### ISSUE THREAD

**Issue by shanemgrey** [SublimeText-Markdown/MarkdownEditing#229]
When I have the syntax set to Markdown in any of the flavors, ST3 (3065) applies the available tab completions as if my .md file is .html.

For example, type the word "details" and hit tab or enter and it inserts a snippet. (this example may be html5 only, but other html examples like br also have this behaviour.

I have Markdown Editing and MarkdownPreview installed. 

I'm not sure this is a MarkdownEditing issue, a ST3 issue, or a config issue on my setup.  But I can't find any forum etc for this plugin, so added it here.

The .txt doesn't offer html tab completions. 

Is there a way to turn this off for this file type? Or better yet, give it tab completions of it's own?

**Comment by felixhao28** [comment]
It actually makes sense because markdown is initially designed for making web pages, so markdown is considered as a sub scope of html. It is not a ST3 issue or a config issue on your side. It is a designed behavior of this plugin.

However, if this really troubles you, the only workaround I can think of is to turn off the tab completion globally.

Providing a markdown specific completion sounds like an interesting idea though.

**Comment by damiendr** [comment]
This has bugged me for ages too. I use markdown to write text that isn't web pages, and HTML completions keep popping up when I want unicode completions — for instance `\pi` completes to `<picture></picture>` instead of `π`.

Here's a workaround. Extract the HTML package and open the file `html_completions.py`:

```python
    def on_query_completions(self, view, prefix, locations):
        # Only trigger within HTML
        if not view.match_selector(locations[0], "text.html - source"):
            return []
```

This matches all HTML that isn't tagged as source. Let's exclude markdown too:
```python
if not view.match_selector(locations[0], "text.html - source - text.html.markdown"):
```

And voilà.

**Comment by Tagirijus** [comment]
Thanks for the help. I still had some issues that inside Markdown other `auto_coplete` stuff was happening. I found out that the package `SublimeCodeIntel` was causing it. I managed to disable autocompletion for Markdown by adding this into my user settings for SublimeCodeIntel:

```
"codeintel_exclude_scopes_from_complete_triggers": ["comment", "markdown"],
```

Hope this might help someone, who might have a similar problem like I did. (-;

**Comment by deathaxe** [comment]
As of ST4107 default HTML completions are disabled in Markdown.

It can be configured via syntax specific setting in `HTML.sublime-settings`.

```
    // Controls what scopes default completions will be provided in.
    // Can be a list of strings which are joined before matching.
    "default_completions_selector": [
        // Plain HTML
        "text.html - source - string - text.html.markdown, ",
        // Embedded HTML blocks
        "text.html.embedded - text.html.embedded source, ",
        // Markdown fenced code blocks
        "markup.raw.code-fence text.html - markup.raw.code-fence text.html source"
    ]
```
