### ISSUE TITLE
MarkdownEditing linter has problems with code nested in lists.

### ISSUE THREAD

**Issue by osopolar** [SublimeText-Markdown/MarkdownEditing#249]
The following  GitHub Flavored Markdown (gfm) markup

```md
* Item 1
  - Item 1.1

    ```
# example code for item 1.1
    ```

  - Item 1.2
* Item 2
```

is correct markup to produce the following result:

* Item 1
  - Item 1.1

    ```
# example code for item 1.1
    ```

  - Item 1.2
* Item 2

But the Markdown Linter claims (for `- Item 1.2`):

> line 8: MD005 - Inconsistent indentation for list items at the same level, 0 expected, 2 found
> line 8: MD006 - Consider starting bulleted lists at the beginning of the line, 2 found
> line 8: MD004 - Unordered list style, * expected, - found

**Comment by ttscoff** [comment]
It's not correct, from a linter perspective. This is correct and 
produces the same result.

	* Item 1
	  - Item 1.1
	
	    ```
		 # example code for item 1.1
	    ```
	
	  - Item 1.2
	* Item 2

**Comment by osopolar** [comment]
Why is it not correct from a "linter perspective". If it is valid gfm it should be.
For your example, if I copied it correctly, the linter still gives me:

> line 8: MD004 - Unordered list style, None expected, - found

**Comment by ttscoff** [comment]
Sorry, my email app messed up the code block:

	* Item 1
	    - Item 1.1
	
	    ```
	    # example code for item 1.1
	    ```
	    - Item 1.2
	* Item 2

Linters are anal about spec. Most specs don't have fenced code block parameters, and the ones that do vary, so the linter takes the strictest route, not necessarily the GitHub prescribed route. It requires that the indentation of the fenced block be the same as the indentation of the backticks, and that the backticks be at the same level of indentation as their parent list item.

Of course, the markdown linter will still throw an error about that hashmark because it doesn't distinguish  fenced code and thinks it's an out-of-place headline.

**Comment by felixhao28** [comment]
Well, the real cause is that the empty line before Item 1.2 was considered as a part of indentation for Item 1.2, thus letting Item 1.2 have a 5-length indentation.

I have just fixed this issue. Thanks for reporting.
