### ISSUE TITLE
Update all the syntaxes to new syntax file format

### ISSUE THREAD

**Issue by ghost** [SublimeText-Markdown/MarkdownEditing#324]
Since ST3 now allows for a much easier to work with [syntax file format](http://www.sublimetext.com/docs/3/syntax.html) I would like to suggest changing all the syntaxes of MarkdownEditing (MDE) to the `.sublime-syntax` format. Or, since you probably want backwards compatibility with ST2, providing both formats.

This would have several advantages, but most of all this would allow for derivate plugins of MDE to include required syntaxes in their own syntax. As an example: Even though I am very unexperienced I would like to develop a "plugin" that provides scope selectors and maybe coloring for the syntax of my very often used wiki generator of the name ikiwiki named [ikiwikiEditing](https://github.com/openmedi/ikiwikiEditing). Since I like the features of MDE and don't want to develop a Syntax all by meself, this would allow for easier integration of already done work in future derivate plugins that provide additional syntax on top of the enhanced markdown you already provide.

**Comment by felixhao28** [comment]
This task has been in my mind from the first day `.sublime-syntax` is announced. But I didn't have the determination to do that. And still not.

**Comment by djspiewak** [comment]
@felixhao28 So… the problem with delaying this is that `tmLanguage` files are not entirely compatible with `sublime-syntax` files from an embedding standpoint.  This doesn't show up in trivial cases, but it's relatively easy to see with more complicated things.  For example: a `scala` fenced code block with the most recent Scala mode from [here](https://github.com/sublimehq/Packages).  This breaks markdown highlighting basically instantly, and it appears to be a consequence of the fact that the MarkdownEditing scoping is defined as `tmLanguage` rather than as `sublime-syntax`.

For the time being, this is ok since relatively few people are using the bleeding edge modes from the development project.  But with the next beta release of ST3, basically everyone is going to see it in the form of MarkdownEditing no longer functioning in a large set of cases.

**Comment by wbond** [comment]
We identified what was causing the issue that @djspiewak was posting about. The Oniguruma regex engine that is use for `pop` rules with backreferences was failing on a certain character range. We switched to using a different format, and I've confirmed the Markdown GFM syntax now works properly with the new Scala syntax.
