### ISSUE TITLE
"Add Missing Link Labels" command deleted

### ISSUE THREAD

**Issue by maliayas** [SublimeText-Markdown/MarkdownEditing#379]
It seems  [this](https://github.com/SublimeText-Markdown/MarkdownEditing/commit/802b489e3eec831e00d0049a79688d13f4bea7a2) commit has removed the "Add Missing Link Labels" feature. Was this on purpose? Currently I can't find a command that does that job. The command is still mentioned in `Default.sublime-commands` btw.

**Comment by felixhao28** [comment]
`Organize References` gives you a list of missing links. I think that is close enough.

**Comment by felixhao28** [comment]
> The command is still mentioned in Default.sublime-commands

I will fix that.

**Comment by maliayas** [comment]
But why do we remove it? It was a useful command.

18 Ağustos 2016 05:49:26 EEST, Felix Hao <notifications@github.com> yazdı:

**Comment by felixhao28** [comment]
That is because I remember when I was writing that commit, someone complained references/footnotes always inserted at the end of the document, while he prefers end of the paragraph. And I thought about adding a config to toggle that behavior on/off but then I realized it is potentially different based on the length of the document rather than one person's preference. So we can just show the missing labels to users and let them decide where to put them.

There is no harm bringing it back though. I am ok with both having this feature or not having it.

**Comment by maliayas** [comment]
Hmm, I see. We should bring it back, I believe.

18 Ağustos 2016 13:19:27 EEST, Felix Hao <notifications@github.com> yazdı:
