### ISSUE TITLE
Support Russian keyboard layout for wrapped

### ISSUE THREAD

**Issue by Kristinita** [SublimeText-Markdown/MarkdownEditing#385]
I use Markdown GFM syntax. 

What happens if I wrap text when I have an English keyboard layout enabled:

![English keyboard layout](http://i.imgur.com/1GisNjw.gif)

Now if I have Russian keyboard layout:

![Russian keyboard layout](http://i.imgur.com/NPCS7SB.gif)

To wrap the text in the code, in braces or in brackets, 

![Keyboard](http://i.imgur.com/HgMKkbE.png)

I have to switch the layout. It is not comfortable. 

Please add support for Russian keyboard layout to wrap text.

Thanks.

**Comment by felixhao28** [comment]
Yeah shortcuts on non-US keyboard layouts are not well supported on ST. I saw your PR and it looks fine but since any change to the keymap affects all users so I have a few concerns:

1. Are the Russian characters you added (`ё Ё № Ю х Х Ъ`) used in another language?
1. If so, will the speakers of that language prefer another layout other than Russian keyboard layout?
1. Is there any more Russian layout? How will your solution affect those users?

**Comment by deathaxe** [comment]
ST4 comes along with some changes about handling key locations. Still not supporting different keyboard layouts though as it would mean to provide language/region specific bindings.

I guess the only solution is to create personal overrides.
