### ISSUE TITLE
Full header lines no longer available for themes

### ISSUE THREAD

**Issue by todgillespie** [SublimeText-Markdown/MarkdownEditing#472]
Hi there,

With a recent update (2.2.4 or 2.2.5), the markup.heading.markdown scope no longer includes the full editor line for highlighting markdown headers.

However, markup.heading.markdown is not defined in the Markdown sublime-syntax file. The new syntax file has a node for punctuation.definition.heading.markdown, but it doesn't seem to define markup.heading.markdown, unless I'm missing something. Is that scope inherited from somewhere else?

How can I override that node, and redefine it so that the end case is just "\n" as before?

Thank you!

**Comment by felixhao28** [comment]
Sorry I don't understand the issue.

> no longer includes the full editor line for highlighting markdown headers.

What is the highlight you expected?


> markup.heading.markdown is not defined in the Markdown sublime-syntax file

[It is defined](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/b957ccde03648c2b99922495c9de78561fe7c7a3/Markdown.sublime-syntax#L650)

> and redefine it so that the end case is just "\n" as before?

The new syntax file is auto-converted from the old tmLanguage. So theoretically the behavior should not change.

**Comment by todgillespie** [comment]
Hello and thank you for your response! 

My apologies, I should have been more clear.

The line in the theme file you reference contains a regex match to the hashmark `#` heading **punctuation** of a Markdown heading, with the selector called `punctuation.definition.heading.markdown`. The previous behavior seemed to match the whole heading line-- including the entire heading text all the way up to the `\n`. I had overrides in my local version that made changes to the full heading, and those went away with this update.

Since there's no spec in the MarkdownEditing.tmTheme file for the full heading selector (`markup.heading.markdown`) maybe the change happened downstream.

In the meantime I have grown fond of the new behavior,  so it's ok for me to close this issue.

Thanks again for your response!

**Comment by felixhao28** [comment]
> The previous behavior seemed to match the whole heading line

That sounds wrong. `punctuation` should only match, you know, the punctuation like the hashmark. Anyway according to you it's fixed now.

> I had overrides in my local version that made changes to the full heading

If you want a different style for the whole line of heading, consider customize the theme for `markup.heading.markdown` scope instead.

> Since there's no spec in the MarkdownEditing.tmTheme file for the full heading selector (markup.heading.markdown)

[There is one](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/b957ccde03648c2b99922495c9de78561fe7c7a3/MarkdownEditor.tmTheme#L485). However `punctuation.definition.heading.markdown` and `entity.name.section.markdown` will override it on any conflicts.

Since the original issue is gone I am closing the issue. Feel free to reopen it if it still bugs you.
