### ISSUE TITLE
MarkdownEditing error stops Sublime Text 2 from launching

### ISSUE THREAD

**Issue by ianpaul** [SublimeText-Markdown/MarkdownEditing#502]
Last week I started seeing an error in Sublime Text 2 with the MarkdownEditing package. Ultimately, it made it impossible to launch the program and I had to delete the package directory manually. The error message was the following: 

> Error trying to parse settings: Trailing comma before closing bracket in 
C:\Users\username\AppData\Roaming\Sublime Text 2\Packages\MarkdownEditing\Markdown(Standard).sublime-settings:63:3

I tried to fix this myself by erasing the comma on line 62 before the bracket on line 63, but then I got the same error message with a different ending "....Markdown(Standard).sublime-settings:145:3. So I dumped the comma on line 143. Then I closed and opened Sublime and I got trailing comma errors for "74:3" and "68:3" and those lines are commented out. So I don't know what the problem is, but it makes this package unusable (at least for me) with Sublime Text 2 on Windows 10.

**Comment by SofaCitizen** [comment]
There is actually the same error in three files:

``
Sublime Text 2/Packages/MultiMarkdown.sublime-settings:63:3
Sublime Text 2/Packages/MarkdownEditing/Markdown (Standard).sublime-settings:63:3
Sublime Text 2/Packages/MarkdownEditing/Markdown.sublime-settings:74:3
``

Trailing commas are not allowed in the JSON spec and so the fix is to replace
`` 
"additional_arguments": [],
``
with 
`` 
"additional_arguments": []
``

However, I also had to remove all the comments because I have a JSON validator installed and comments are also not allowed within the JSON spec. Sublime Text itself doesn't mind comments so you may be OK to skip that part.

**Comment by m-z-b** [comment]
The error in Markdown(standard).sublime-settings at 145:3 can also be fixed by removing a trailing comma, changing:

```
        // Open the page referenced
        "mde.keymap_disable.open_page": true,
        // Make page reference
}
```
to:
```
        // Open the page referenced
        "mde.keymap_disable.open_page": true
        // Make page reference
}

```

**Comment by ianpaul** [comment]
Thanks everyone. This time around I edited all three files that @SofaCitizen suggested, and the comma that @m-z-b pointed out. That seems to have done the trick.

**Comment by felixhao28** [comment]
This issue will be fixed in the next release. Sorry everyone. Then again only the latest stable version of ST3 is tested and guaranteed to work. I recommend upgrading to ST3 if possible.
