### ISSUE TITLE
Why the "----" syntax on wiki pages?

### ISSUE THREAD

**Issue by domsl** [SublimeText-Markdown/MarkdownEditing#516]
Hello - quick question:

When you open a new wiki page then MDE automatically adds:
```
# test



----
```
Why the 4 new lines and then `---- `?

I know `----`  creates a dividing line, but then I do not understand why you would have those newlines?
I am assuming this complies to some wiki format syntax, but I could find any wiki that uses that, so I am confused.

**Comment by felixhao28** [comment]
@dave-ellis Any idea?

**Comment by dave-ellis** [comment]
Yes, the idea is that the content of the page would be entered between the header at the top and the dividing line at the bottom.  Then any tag pages would be listed as page references at the bottom.

For example:
```
    # Page Header

   The page content would go here.

   ----

    [[TagExamples]] [[TagTemplates]]
```

This is currently controlled by the `PrepareFromTemplateCommand` class in `prepare_from_template.py`. 

Currently this always creates a page in this style, however the idea is expand this code to use a configured template to generate the new page, so that the user can define how they want their new pages formatted.

**Comment by dave-ellis** [comment]
However, I can see how this would be confusing to a new user, so maybe the default template should just have the header and two blank lines as that would be more likely to match up with expectations.

**Comment by dave-ellis** [comment]
I have created a PR that implements these changes.  See https://github.com/SublimeText-Markdown/MarkdownEditing/pull/520

**Comment by felixhao28** [comment]
But is it not that `----` will be read as a mark for "Second Level Title"? Is this a commonly-used wiki-specific syntax to separate content and tags with four dashes?

**Comment by dave-ellis** [comment]
If the four dashes were directly under some text then yes it would be a
heading.

And no it isn't 'standard', it just a use of separator.

**Comment by felixhao28** [comment]
I see. Let's make the default template as little opinionated as possible then.

**Comment by domsl** [comment]
Alright, thanks for the information. :)
