### ISSUE TITLE
"Apparent recursion" error loading syntax file

### ISSUE THREAD

**Issue by agj** [SublimeText-Markdown/MarkdownEditing#533]
First of all thank you, I love this package and have been using it for a long time now. Recently however, I don't know if after an automatic update of MarkdownEditing or of Sublime, I'm getting this error whenever I open a markdown file:

    Error loading syntax file "Packages/MarkdownEditing/Markdown.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

I am under macOS High Sierra 10.13.6, and I have Sublime Text 3 version 3.1.1 build 3176, with the latest MarkdownEditing (I don't know how to check the version of a package...)

I didn't find any other issues here with the same error. I wonder what's causing it...?

**Comment by dissolved** [comment]
I get the same error... I've found various mentions of it here mostly mention disabling it. But that doesn't seem very practical! I actually want syntax highlighting for my markdown.

**Comment by jayliu50** [comment]
I find that by enabling or disabling `JavaScriptNext - ES6 Syntax` I can get the issue to go away or come back. This what you find as well? I'm on Sierra, ST3, 3176. 

Looking at other threads, it does seem like JavaScriptNext is the culprit: 

https://github.com/Benvie/JavaScriptNext.tmLanguage/issues/7

**Comment by agj** [comment]
Wow, you're right, @jayliu50! It does work when I disable that package. I wonder why the error is so uninformative, though... Also, I tried installing the "JavaScript Ultimate" package as a replacement and I still got the same error. But, it does seem to mean that the problem lies in Sublime Text or its APIs...

**Comment by suifengtec** [comment]
thx @jayliu50 

it works fine  after I disable that package.

**Comment by eban5** [comment]
Disabling _JavascriptNext - ES6 Syntax_ also worked for me, also on macOS High Sierra 10.13.6 Sublime Text 3 version 3.1.1 build 3176. Using the latest MarkdownEditing. This was driving me nuts, thanks!

**Comment by Zeeker** [comment]
For me the culprit was [`Naomi`](https://github.com/borela/naomi)

**Comment by amsul** [comment]
After months of those annoying popups..I can also confirm, disabling *JavascriptNext - ES6 Syntax* fixes the issue.

Thanks @eban5 🙌

**Comment by duranivan** [comment]
I don't have JavascriptNext nor Naomi installed, but still face the same issue. I do have however Javascript (Babel) installed.

Reading other posts about this (e.g. [here](https://forum.sublimetext.com/t/cannot-load-markdown-files-apparent-recursion-within-a-with-prototype-action-25000-context-sanity-limit-hit/36720)), I realized that the problem is being caused by disabling the built-in Javascript syntax. All these alternative Javascript syntax packages require or suggest to have the built-in Javascript disabled, and so if I enable it back, the problem goes away.

I do however want/need to keep the built-in Javascript disabled so other packages such Vue Syntax Highlighting uses the Babel syntax I like instead of the built-in one. But then my Markdown files will lack the benefits of MarkdownEditing GFM.

Is there any way that MarkdonwEditing GFM uses the syntax highlighting currently active for your normal .js files?

**Comment by skipjack** [comment]
Here's a link to the corresponding `Naomi` ticket:

https://github.com/borela/naomi/issues/117

**Comment by zedtux** [comment]
Thank you @skipjack for pointing to the Noami's issue!

**Comment by deathaxe** [comment]
This shouldn't happen anymore due to `embed` being used to included 3rd-party packages.
