### ISSUE TITLE
Shift+tab not unindenting previous list item

### ISSUE THREAD

**Issue by dsmaynard** [SublimeText-Markdown/MarkdownEditing#545]
I am trying to figure out how to get the unindent feature to work. If I have a list with 2 levels, and I press shift+tab immediately after creating a new bullet point for the second level, it successfully unindents the bullet and switches the indent symbol from - to *. However, if I go on and create several new bullet points (either first or second level) and then go back up to unindent a previous 2nd-level list item, it doesn't unindent unless I move the cursor to before the indent symbol, and even then, it doesn't switch the symbol back, keeping it as a level 2 list. 

Is there some way to fix this?

**Comment by MitchAllain** [comment]
This was likely by design to preserve the tab character. The indent regex is:
https://github.com/SublimeText-Markdown/MarkdownEditing/blob/291fc854df88df9df12923ae68461d4e72f3f3ee/Default%20(Linux).sublime-keymap#L60-L66

So the line has to be essentially empty with your cursor directly after the list identifier (plus some whitespace).

You can play with the regex filters in your User `sublime-keymap` file to override the default behavior, which I found useful. Note that if you allow word characters `\w` to precede the command, you may step on the normal autocomplete behavior of tab.
