### ISSUE TITLE
Any plan for solarized color themes?

### ISSUE THREAD

**Issue by liuyigh** [SublimeText-Markdown/MarkdownEditing#570]
Thanks for this great plugin. Given the popularity of solarized themes (included in SL3 "Color Scheme - default" package), is there any plan to match solarized light and dark themes for MarkdownEditing?

Thanks!

**Comment by deathaxe** [comment]
Due to the amount of embedded syntaxes in fenced code blocks the best solution probably was to just default on general available color schemes. Writing good color schemes for all syntaxes is a quite massive task.

Next release will come with a change which keeps global color scheme by default and suggests those builtins optionally only.

**Comment by liuyigh** [comment]
"keeps global color scheme by default" will do.

**Comment by liuyigh** [comment]
Btw, solarized themes are default SL3 themes. (included in SL3 "Color Scheme - default" package)
