### ISSUE TITLE
How to disable automatic space insertion after heading hashes?

### ISSUE THREAD

**Issue by szafranek** [SublimeText-Markdown/MarkdownEditing#643]
One of the things that changed after the update to latest version is that starting a heading with a `#` character automatically inserts a space after it.

Is there a setting to disable this behavior? I couldn't find it.

**Comment by deathaxe** [comment]
That's a stupid side effect of the `set_headings_level` function being called by typing `#` in order to keep closing hashtags balanced (if present). To disable it, set `"mde.auto_match_heading_hashes": false`.

Haven't put too much effort in fixing that edge case as heading require that space anyway and typing further `#` would add them as expected.

**Comment by szafranek** [comment]
Thank you, that works for me!
