### ISSUE TITLE
Configuration edit issues

### ISSUE THREAD

**Issue by stdedos** [SublimeText-Markdown/MarkdownEditing#667]
According to https://sublimetext-markdown.github.io/MarkdownEditing/config/#change-configuration

> In Main Menu navigate to: Preferences > Package Preferences > MarkdownEditing
> In Command Palette look for: Preferences: MarkdownEditing ...

However, both of them open the Sublime-Text-wide settings, not the extension settings.

**Comment by deathaxe** [comment]
That's correct and expected. All MarkdownEditing related settings are to be added to _Packages/User/Preferences.sublime-settings_. That's why all of them are prefixed with `mde.`. As a result all settings can be global/per project/per syntax/per view or different in distraction free mode.

This is described in the very first sentence/paragraph of the linked page.

**Comment by stdedos** [comment]
My bad for reading the page upwards 😅

**Comment by stdedos** [comment]
One of the reasons I got "confused" with this new kind of settings-handling, was that e.g. `MarkdownEditing: Select Color Scheme` is not found anywhere in the `Preferences > Package Preferences > MarkdownEditing` preferences - which I assumed to be the place to find it.

... of course, it being in `Packages/User/Markdown.sublime-settings` makes more sense, I guess? :/

**Comment by deathaxe** [comment]
>  ...  `MarkdownEditing: Select Color Scheme` is not found anywhere in ...

Could easily be added.

> ... of course, it being in Packages/User/Markdown.sublime-settings makes more sense, I guess? 

No it doesn't, because this is already a syntax specific settings file, which would cause the user settings not to be applied to _MultiMarkdown_ for instance. It would also prevent project specific settings as those are of lower priority than syntax specific ones.

**Comment by stdedos** [comment]
> > ...  `MarkdownEditing: Select Color Scheme` is not found anywhere in ...
> 
> The menu item is only visible if a markdown file is open. The command is inherited from base MdeTextCommand, which hides all commands from Command Palette if a view doesn't show a markdown file.

I think the pre-edited response was more fitting (i.e. I was talking about _the result_ of the command, not the command being conditionally hidden)

(but the command being hidden in non-Markdown files was kiiinda confusing too 😅. At least it's done smartly e.g. `Settings: MarkdownEditing` is not conditional)

**Comment by deathaxe** [comment]
You talked about "not finding the command in main menu". As the command actually exists in main menu the pre-edited response "Can be added" doesn't fit, technically. It just needs to be made visible unconditionally.

**Comment by stdedos** [comment]
> You talked about "not finding the command in main menu".

Maybe I should revise what I've said :-D

> ```
> -`MarkdownEditing: Select Color Scheme` is not found anywhere in the `Preferences > Package Preferences > MarkdownEditing` preferences
> +The result of changing `MarkdownEditing: Select Color Scheme` is not found anywhere in the `Preferences > Package Preferences > MarkdownEditing` preferences (where I'd expect it to be visible)
> ```

**Comment by deathaxe** [comment]
Color schemes are assigned to syntax specific settings (e.g.: Markdown.sublime-settings) as those are not designed for normal source code.

The one and only use of _MarkdownEditing: Select Color Scheme_ is to set `color_schem` in syntax specific settings. And now that I think about it: that's exactly the reason for the command not to be visible if the active view doesn't display a markdown file. This command would assign one of those color schemes to any (wrong/unwanted) syntax otherwise.

So you'll find the setting when calling _Preferences: Edit Settings - Syntax Specific_ while a markdown file is open.

I could probalby add a `mde_edit_settings_syntax_specific` command, which displays MDE's Preferences on the left and the `Markdown.sublime-settings` file on the right, but I can't resolve ST's scattered settings files issues.

**Comment by stdedos** [comment]
No worries then! If it's that complicated/"random" of it working more, then it maybe isn't worth the effort.

Thank you for today's discussions 😄

**Comment by 0xdevalias** [comment]
> That's correct and expected. All MarkdownEditing related settings are to be added to _Packages/User/Preferences.sublime-settings_. That's why all of them are prefixed with `mde.`

- https://sublimetext-markdown.github.io/MarkdownEditing/config/#change-configuration

@deathaxe I'm curious why the main settings were implemented this way, rather than in what seems to be the more standard pattern of having a standalone settings file/user settings file for each plugin (rather than being merged with the main settings).

Personally I prefer this neat 'separation of concerns' rather than needing to clutter up one settings file with unrelated config.

**Comment by deathaxe** [comment]
MarkdownEditing never used package-specific settings. It just changed from syntax-specific to global user settings.

Both _Preferences.sublime-settings_ and _Distraction Free.sublime-settings_ are default settings files defined by Sublime Text.

MarkdownEditing just re-uses those files to locate settings within as this allows all settings to be any of:

- global
- project-specific
- view-specific
- syntax-specific
- mode-specific (Distraction Free on/off)

by following ST's default settings files hierarchy (see: https://www.sublimetext.com/docs/settings.html#settings-files)

None of package-specific settings (e.g.: MarkdownEditing.sublime-settings) would satisfy that.

**Comment by 0xdevalias** [comment]
Hrmm, fair enough. Thanks for the detailed info :)
