### ISSUE TITLE
Unable to find LinkedReference

### ISSUE THREAD

**Issue by Manaus** [SublimeText-Markdown/MarkdownEditing#679]
Hitting <kbd>F12</kbd> on a linked reference on Windows ST3 I get this note in the status bar. For example F12 on `[[MyFile]]` does not find MyFile.md lying beside the file I'm working on. Nothing useful from the console either. 

Nor does hitting <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>D</kbd> open up a Wiki page of mine, as pointed out on the [Usage page](http://sublimetext-markdown.github.io/MarkdownEditing/usage/#wiki)

**Comment by deathaxe** [comment]
The <kbd>F12</kbd> binding is implemented for normal references only.

Usage docs seem out dated. Opening a wiki page is bound to <kbd>ctrl+alt+d</kbd>, but it is disabled by default via Preferences - I guess because it may conflict with normal chars on some keyboard layouts.

Using <kbd>F12</kbd> to open wiki pages seems quite interesting though.
