### ISSUE TITLE
How to use YAML frontmatter?

### ISSUE THREAD

**Issue by arcturus140** [SublimeText-Markdown/MarkdownEditing#690]
with the latest update my YAML header are no longer by scope `source.yaml`. Is there any way to handle YAML frontmatter?

**Comment by deathaxe** [comment]
Nothing has changed with regards to YAML frontmatter.

![grafik](https://user-images.githubusercontent.com/16542113/168357658-9a52c045-45f1-4fa0-9365-fc7086fa51a9.png)

**Comment by arcturus140** [comment]
I started ST4 in safe mode and installed MarkdownEditing, the scopes on line 2 are:

```
text.html.markdown.multimarkdown meta.content.multimarkdown markup.heading.2.markdown entity.name.section.markdown
```

Sublime Core uses the following scopes:

```
text.html.markdown.multimarkdown meta.content.multimarkdown text.html.markdown meta.frontmatter.markdown source.yaml.embedded.markdown source.yaml string.unquoted.plain.out.yaml entity.name.tag.yaml
```
I think that `source.yaml` is missing in `MarkdownEditing` for `MultiMarkdown` syntax.

**Comment by deathaxe** [comment]
If you want YAML frontmatter, use Markdown.sublime-syntax

MultiMarkdown doesn't support YAML frontmatter. It uses its own simple key-value style of meta data at the beginning of a document, which may look very similar to YAML in the first place, but doesn't support nested objects etc.

for differences see: https://stackoverflow.com/questions/44215896/markdown-metadata-format

ST opens markdown files using Markdown.sublime-syntax (out of the box), which highlights YAML frontmatter. MultiMarkdown is used only if actively assigned by user or if `format: complete` is found in the very first line.

The style of metadata is the only difference between Merkdown.sublime-syntax and MultiMarkdown.sublime-syntax.

Note: ST4's default MultiMarkdown.sublime-syntax highlighting YAML frontmatter is a bug, which will be fixed in one of the next ST4 releases.

**Comment by deathaxe** [comment]
Here's an example of how multimarkdown 6.6.0 translates YAML frontmatter of a markdown (on the left) to html (on the right).

![grafik](https://user-images.githubusercontent.com/16542113/168467955-f8bf480b-6e8d-4aa8-973f-2a7b230acc5d.png)

Highlighting of markdown content using Multimarkdown.sublime-syntax matches the html output!

**Comment by deathaxe** [comment]
The previous screenshot was made with `multimarkdown -b -c test.md`. Omitting `-c` flag results in first `---` being parsed as beginning of frontmatter. This will be fixed in the next release.
