### ISSUE TITLE
Code blocks with 3 backticks not highlighted

### ISSUE THREAD

**Issue by ricab** [SublimeText-Markdown/MarkdownEditing#706]
Code blocks marked with \`\`\` are not being highlighted, unless syntax is specified. \`\`\`plain not working either:

![Screenshot from 2022-08-19 19-06-27](https://user-images.githubusercontent.com/6698114/185680575-a3c493f8-a4d6-4004-8d91-65ee513e13aa.png)

**Comment by deathaxe** [comment]
Fenced code blocks are scoped `markup.raw` by default. 

- This applies to those with no, unknown or `plain` syntax name.
- Those with known syntax names such as `sh`, `py`, ... are highlighted using corresponding syntax definitions.

There's no way to guess syntaxes nor to dynamically apply one during runtime.

If missing background color is the issue, it's up to a color scheme to apply it on `makrup.raw`. See how Mariana handles it:

![grafik](https://user-images.githubusercontent.com/16542113/185686045-80781752-34ac-408b-9409-e9daf94830ae.png)

Otherwise that's working as expected.

**Comment by ricab** [comment]
Theme's fault, gotcha.
