### ISSUE TITLE
Missing color scheme & syntax after 3.1.13 update

### ISSUE THREAD

**Issue by infotexture** [SublimeText-Markdown/MarkdownEditing#762]
After updating MarkdownEditing to v3.1.13, Sublime Text can't seem to find the color schemes and syntaxes any more:

> **Error loading colour scheme**
> 
> MarkdownEditor.sublime-color-scheme: Unable to find MarkdownEditor.sublime-color-
scheme

> Error loading syntax file "Packages/MarkdownEditing/syntaxes/Markdown.sublime-syntax": Unable to read Packages/MarkdownEditing/syntaxes/Markdown.sublime-syntax

**Comment by deathaxe** [comment]
Color schemes haven't been touched.

The `Error loading colour scheme` may be raised due to MarkdownEditing being temporarily unavailable during package upgrade, if the color scheme is active and/or a user defined override exists.

The same is even more likely for syntax files, because MarkdownEditing creates a _Markdown.sublime-package_ to override ST's default markdown syntax, so other packages can use/inherit from MDE's markdown syntax.

Preventing that error would require to dynamically find all related packages/syntaxes and temporarily disable them during override creation - as well as preserving syntax assignment of all open views.

That's possible but unlikely to be implemented anytime soon.

---

I see the syntax error once after an update, if markdown files are open, but can continue after dismissing the dialog without issues.

Thing should however get back to normal after a restart.

If not, maybe the downloaded package is corrupted. Maybe removing and reinstalling helps?

---

CI tests of this repo run syntax tests against ST3211, ST4107, ST4126 and ST4143, ST4152 and ST4169 as well as unittests on ST3211 and ST4169.

Things also seem normal when manually installing them on ST3176 or ST4107, both by Package Control or by downloading the package files from Github releases.

**Comment by infotexture** [comment]
> Maybe removing and reinstalling helps?

Thanks for the background, makes sense. That solved it, closing.

Thanks for your work here. 🙏
